# Generated by Django 5.2.11 on 2026-03-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='to_user',
            new_name='creditor',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='from_user',
            new_name='debtor',
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('debtor', 'creditor')},
        ),
        migrations.AddField(
            model_name='expenseparticipant',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal')], default='EQUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='expenseparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_participations', to='expenses.user'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseparticipant',
            unique_together={('expense', 'user')},
        ),
    ]
